version: '3.8'

services:
  auth-service:
    image: golang:1.25-alpine
    ports:
      - "8081:8080"
    volumes:
      - .:/app
      - go-modules:/go/pkg/mod
    working_dir: /app/services/authentication-service
    command: sh -c "go mod download && go run main.go"
    networks:
      - restaurant-network
    restart: unless-stopped

  order-service:
    image: golang:1.25-alpine
    ports:
      - "8082:8080"
    volumes:
      - .:/app
      - go-modules:/go/pkg/mod
    working_dir: /app/services/order-service
    command: sh -c "go mod download && go run main.go"
    networks:
      - restaurant-network
    restart: unless-stopped

  product-service:
    image: golang:1.25-alpine
    ports:
      - "8083:8080"
    volumes:
      - .:/app
      - go-modules:/go/pkg/mod
    working_dir: /app/services/product-service
    command: sh -c "go mod download && go run main.go"
    networks:
      - restaurant-network
    restart: unless-stopped

volumes:
  go-modules:

networks:
  restaurant-network:
    driver: bridge